### ISSUE TITLE
question about best usage when using for testing

### ISSUE THREAD

**Issue by joeblew99** [comail/colog#3]
Does it parse errors on Tests ?

, i was hoping that doing a t.Error("alert: blah"), would display in Red.
In the below example, i end up having to do a t.Error & a log.Println(alert), in order to get the RED visual warning.

I know this is picky ! But when you have lots of tests, looking at your Bash Terminal can get really slow trying to hunt for it. The visual aids are great.

Any advice welcome, as you can see what i can getting at.

```
func init() {

    colog.Register()
    colog.ParseFields(true)
    colog.SetMinLevel(colog.LWarning)
    colog.SetDefaultLevel(colog.LInfo)
}

func TestGetProduct(t *testing.T) {
    t.Error("alert: thrown from t.Errror !!")
    log.Println("alert: thrown from log.Print !!")


}

```

Bash Terminal has:

```
[ alert ] 2016/04/15 18:58:35 thrown from log.Print !!                                          
--- FAIL: TestGetProducts_CategoryOnly (0.01s)
    products_test.go:105: alert: thrown from t.Errro !!
    products_test.go:112: Passed

```

**Comment by bictorman** [comment]
I’m afraid this is not possible, at least I wouldn’t know how. The testing package [prints directly with fmt](https://github.com/golang/go/blob/release-branch.go1.6/src/testing/testing.go#L533).

If you really want this, the only thing you could do is implement [your own error methods](https://github.com/golang/go/blob/release-branch.go1.6/src/testing/testing.go#L369):

``` go
func TestGetProduct(t *testing.T) {
    Errorf(t, "alert: thrown from t.Errror %d !!", 42)
    log.Println("alert: thrown from log.Print !!")
}

func Errorf(t *testing.T, format string, args ...interface{}) {
    log.Printf(format, args...)
    t.Fail()
}
```

But that’s a bad idea, because the logs would show up while running before the test result reports, and if you execute the tests in parallel the messages could get all mixed up.

**Comment by joeblew99** [comment]
Thanks for quick Response. Well, i just wrote some util functions to help, as you also suggested.

All great, and thanks for this package.
